// frontend-vue/src/components/FormField.vue
<template>
  <div class="flex flex-col gap-y-2">
    <label :id="id">{{ label }}</label>
    <input
      :type="type"
      :id="id"
      v-model="model"
      class="h-8 px-2 text-sm border-b border-black bg-transparent"
    />
    <span class="text-red" v:if="errors">{{ errors }}</span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  label: string;
  id: string;
  type: string;
  errors: string;
}>();

const model = defineModel();
</script>

// frontend-react/src/components/FormField.tsx
type FormField = {
  label: string;
  id: string;
  type: string;
  name: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  errors: string;
};

export default function FormField(props: FormField) {
  return (
    <div className="flex flex-col gap-y-2">
      <label htmlFor={props.id}>{props.label}</label>
      <input
        id={props.id}
        type={props.type}
        name={props.name}
        value={props.value}
        onChange={props.onChange}
        className="h-8 px-2 text-sm border-b border-black bg-transparent"
      />
      {props.errors && <span className="text-red">{props.errors}</span>}
    </div>
  );
}
