// frontend-react/src/features/homepage/IndexView.tsx
import Title from "../common/Title";
import LinkTo from "../common/LinkTo";
import UserView from "../user/UserView";
import { useTokenStore } from "../../store/user-store";

export default function IndexView() {
  // const isAuth = tokenStore.getState().isAuth;

  const isAuth = !!useTokenStore((s) => s.token);

  return (
    <div className="container mx-auto px-4 flex flex-col items-center">
      <Title title="Hello to YourWallet" />
      {isAuth ?
        <UserView></UserView>
        : <div className="py-8 flex flex-col gap-y-4 items-center">
          <LinkTo name="registration"></LinkTo>
          <LinkTo name="login"></LinkTo>
        </div>
      }
    </div>
  );
}

// frontend-vue/src/view/IndexView.vue
<template>
  <div class="pt-6 flex flex-col items-center h-screen">
    <div class="container mx-auto px-4 grow">
      <div v-if="!isAuth" class="flex flex-col gap-y-4 items-center">
        <Title title="Welcome to YourWallet"></Title>
        <LinkToPage to="/registration" name="Registration" />
        <LinkToPage to="/login" name="Login" />
      </div>
      <div class="w-full" v-if="isAuth">
        <UserView />
      </div>
    </div>
    <Footer></Footer>
  </div>
</template>

<script setup lang="ts">
import Title from "../components/Title.vue";
import LinkToPage from "../components/LinkToPage.vue";
import { isAuth, updateUserStore } from "../store/user-store";
import UserView from "./UserView.vue";
import Footer from "../components/Footer.vue";

if (isAuth) {
  updateUserStore();
}
</script>
