// frontend-vue/src/view/IndexView.vue
<template>
  <div class="container mx-auto px-4 flex flex-col items-center">
    <h1 class="py-8 text-2xl font-bold">Hello to YourWallet</h1>
    <div class="py-8">
      <RouterLink
        to="/registration"
        class="bg-black text-white rounded border border-solid border-black px-4 py-2 transition hover:bg-white hover:text-black"
        >Registration</RouterLink
      >
    </div>
  </div>
</template>

// frontend-react/src/view/IndexView.tsx
import { NavLink } from "react-router-dom";
import Title from "../components/Title";

export default function IndexView() {
  return (
    <div className="container mx-auto px-4 flex flex-col items-center">
      <Title title="Hello to YourWallet"/>
      <div className="py-8">
        <NavLink
          to="/registration"
          className="bg-black text-white rounded border border-solid border-black px-4 py-2 transition hover:bg-white hover:text-black"
        >
          Registration
        </NavLink>
      </div>
    </div>
  );
}
